### ISSUE TITLE
How we can install this tool and can we use for mysql

### ISSUE THREAD

**Issue by sahubharat25** [cmu-db/ottertune#5]
Hi ,

Is ottertune is ready for production use.

**Comment by dvanaken** [comment]
At this point, OtterTune is more of a prototype because there are some aspects of its capabilities that may limit its usefulness in a production setting. Here are some of the problems I'm working on solving:

1. OtterTune requires the user to list the hardware that the DBMS is deployed on. In our paper, what OtterTune collected was the EC2 instance type. This is a problem because we do not want (1) OtterTune to be specific to EC2, (2) to assume that the user knows the hardware the DBMS is running on, and (3) to assume that OtterTune will have remote access to the DBMS's host machine (which is the case with DBaaS deployments). To solve this problem, we're researching how to automatically detect the hardware capabilities of the DBMS's host machine using only a standard API like JDBC.

2. Many configuration knobs have tradeoffs that must be considered while tuning. For example, reducing the number of checkpoints will improve I/O performance but will also increase crash recovery time. OtterTune currently optimizes a DBMS's configuration for a single target objective, like the latency. But the knob that controls the checkpoint frequency should be tuned for both the latency and, for example, the recovery time since only tuning for the latency could result in an unrealistic setting.

**Comment by ivanbaldo** [comment]
Regarding point 1:
What information does OtterTune require?
I think that it could have different providers, one being manual input (a file for example), another SSH access, and maybe other through JDBC "probing" things as you mention.

Regarding point 2:
It would be very nice that OtterTune estimated the time required for recovery and the user just simply put an upper limit on recovery time, but as an intermediate short term solution, it should simply have constraints specified by the user, like the checkpoint frequency, etc.

After reaching a point of install-ability and usability, people will start sending patches, so, the sooner it can be usefully deployed, with some appropriate documentation, the better for the project success (in my opinion of course).

Anyway, thanks a lot for the paper and the tool!!!
Best wishes!

**Comment by vmohan83** [comment]
I would like to appreciate and thank you for the tool. I understand, it is not currently available for production use due to some limitations. I would like to try this tool. the source code are available in GIT,   I have gone through paper, its a great one which provides very useful insight of the tool but couldn't find any detailed steps for trying out. Do you have any reference for this?

**Comment by dvanaken** [comment]
Site is now under construction with more contributors. Please check back for installation/setup instructions soon!
