### ISSUE TITLE
there is missing some file in code

### ISSUE THREAD

**Issue by lilf** [cmu-db/ottertune#6]
hi, i read your code and found some file missing,for example, analysis.preprocessing

there exists 

from .util import NEARZERO
from common.typeutil import is_numeric_matrix, is_lexical_matrix

but i can't find file util  and typeutil

**Comment by oyb001** [comment]
@dvanaken ,The following code statement fails to execute because the file is missing, please provide a file to run.
Thanks!
from .util import stdev_zero
from common.timeutil import stopwatch
from pyDOE import lhs
import dill as pickle
from .util import get_unique_matrix
from experiment import ExpContext, TunerContext
from globals import Paths

**Comment by dvanaken** [comment]
The missing dependencies should be resolved now!
