### ISSUE TITLE
Settings to replicate paper

### ISSUE THREAD

**Issue by stefanocereda** [cmu-db/ottertune#63]
Hi all,
I'm trying to use ottertune to replicate the results obtained in "Automatic Database Management System Tuning Through Large-scale Machine Learning".
More specifically, I'm trying to run the TPC-C workload of OLTP. I've seen that the number of warehouses (scale) has been set to 200, but I can't find the number of terminals nor the weights for the various transaction types. Could you please share the xml configuration file you used?

I'd also like to know for how much time you let the workload run before evaluating the single trial, as I think that the default duration of 10 seconds is too short to obtain stable results. I'm orienting toward longer trials (~10 minutes) and discarding the first minutes to avoid warm up effects, what do you think?

Thanks in advance!

Below is a sample configuration provided by OLTP:
```
<?xml version="1.0"?>
<parameters>

        <!-- Connection details -->
        <dbtype>postgres</dbtype>
        <driver>org.postgresql.Driver</driver>
        <DBUrl>jdbc:postgresql://DB_IP:5432/</DBUrl>
        <username>postgres</username>
        <password>password</password>
        <isolation>TRANSACTION_READ_COMMITTED</isolation>

        <!-- Scale factor is the number of warehouses in TPCC -->
        <scalefactor>2</scalefactor> <!-- instead of 2 -->

        <!-- The workload -->
        <terminals>2</terminals> <!--instead of 2 -->
        <works>
                <work>
                        <time>10</time> <!-- instead of 10 -->
                        <rate>10000</rate>
                        <ratelimited bench="tpcc">true</ratelimited>
                        <weights>45,43,4,4,4</weights>
                </work>
        </works>

        <!-- TPCC specific -->  
        <transactiontypes>
                <transactiontype>
                        <name>NewOrder</name>
                </transactiontype>
                <transactiontype>
                        <name>Payment</name>
                </transactiontype>
                <transactiontype>
                        <name>OrderStatus</name>
                </transactiontype>
                <transactiontype>
                        <name>Delivery</name>
                </transactiontype>
                <transactiontype>
                        <name>StockLevel</name>
                </transactiontype>
        </transactiontypes>
</parameters>
```

**Comment by dvanaken** [comment]
Great!

WRT the time, the TPC-C and YCSB workloads are pretty simple -- in my experiments, I found that a period of 5 minutes was sufficient. You might test this and see if you find the same to be true. For more complex workloads you'd probably need a longer observation period.

You can try launching experiments using the code we've developed so far but do keep in mind that it's still under development and there are bugs/features that we haven't gotten to fixing/implementing yet. We hope to have our initial release out in about a month or two.

Here's the TPC-C config I was using:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<configuration>
<isolation>TRANSACTION_READ_COMMITTED</isolation>
<scalefactor>200</scalefactor>
<terminals>50</terminals>
<works>
<work>
<time>300</time>
<rate>unlimited</rate>
<weights>45</weights>
<weights>43</weights>
<weights>4</weights>
<weights>4</weights>
<weights>4</weights>
</work>
</works>
<transactiontypes>
<transactiontype>
<name>NewOrder</name>
</transactiontype>
<transactiontype>
<name>Payment</name>
</transactiontype>
<transactiontype>
<name>OrderStatus</name>
</transactiontype>
<transactiontype>
<name>Delivery</name>
</transactiontype>
<transactiontype>
<name>StockLevel</name>
</transactiontype>
</transactiontypes>
</configuration>
```

**Comment by stefanodoni** [comment]
Hi,

First of all many thanks for the great work!

I'm also interested in replicating the paper results on the Postgres database. Would you kindly add more detail around the following points:

1) I see something like 2x throughput improvement achieved with the TPC-C workload over the default. 

May you kindly share what is the default Postgres configuration you are comparing to in the paper?

2) Calculation of maximum throughput

I would like to understand how you calculated the throughput figures presented in the paper (e.g. Figure 11). For example, I see Default of about 400 txn/sec and OtterTune of about 900 txn/sec.

Is this number the peak throughput reported by oltpbench during the 5 min run? Is it the average?
Also, is this number obtained by running TPC-C with 50 terminals for both Default and OtterTune configuration? Or you are manually increasing it to account for more throughput that you get with OtterTune.

I ask because from my experience systems can show retrograde throughput. So if 50 terminals are enough to generate ~1000 tnx/sec and this workload is used to stress the Default configuration, it might be that the 400 tnx/sec are the result of thrashing inside the database due to an excessive load.

3) Restoring TPC-C database after each experiment

At the moment, we're launching experiments without clearing the TPC-C database. We are wondering whether if the database should be restored to fully replicate the same conditions, or this is not required?

4) Restoring system state after each experiment

We noticed that a factor that impacts the performance of TPC-C on Postgres is having the Linux page cache warmed up o not.

As you are running short, 5 min experiments, I wonder if you are clearing the operating system caches between experiments.

5) We are replicating your setup on AWS. May you share which storage configuration you use?

Running oltpbench I see that the workload is very IO intensive - it's hard to saturate CPUs. This is true even after we provisioned EBS volumes to reach 2000 IOPS.


Many thanks in advance for you time!

**Comment by dvanaken** [comment]
Hi @stefanodoni - my answers are inline. I think your setup in (5) might be quite different. Hope this helps!

1. It's the default configuration for Postgres 9.3. The only knob changes are to enable statistics collection: track_counts=on, track_io_timing=on

2. It's the average throughput. We use 50 terminals for both the Default & OtterTune configs.

3. We restore the TPC-C database whenever the storage space used on either SSD increased past 75%.

4. Yes, we clear the OS cache between experiments.

5. We used the m3.xlarge instance type for the DBMS server. It comes with two 40GB SSD instance stores which we used instead of EBS. We had the data directory on one of them and the WAL on the other (pg_xlog).

We also configured the following:

(a) Kernel params:
- kernel.shmmax: 8589934592
- kernel.shmall: 2097152
- vm.swappiness: 10
- vm.overcommit_memory: 2
- vm.overcommit_ratio: 80
- vm.dirty_ratio: 80
- vm.dirty_background_bytes: 100000000

(b) XFS with mount options: rw, noatime, inode64

(c) Blockdev readahead: 16384

(d) Scheduler: deadline

(e) Security limits:
- \* soft nofile: 65536
- \* hard nofile: 65536
- \* soft nproc: 131072
- \* hard nproc: 131072
